// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.github.alonwang.transport.protobuf;

public final class Base {
  private Base() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface RequestHeaderOrBuilder extends
          // @@protoc_insertion_point(interface_extends:RequestHeader)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 命令id
     * </pre>
     *
     * <code>int32 commandId = 1;</code>
     *
     * @return The commandId.
     */
    int getCommandId();

    /**
     * <pre>
     * 请求时间戳
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    long getTimestamp();
  }

  /**
   * <pre>
   * *
   * 请求头
   * </pre>
   * <p>
   * Protobuf type {@code RequestHeader}
   */
  public static final class RequestHeader extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:RequestHeader)
          RequestHeaderOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use RequestHeader.newBuilder() to construct.
    private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private RequestHeader() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new RequestHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private RequestHeader(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              commandId_ = input.readInt32();
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_RequestHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_RequestHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.github.alonwang.transport.protobuf.Base.RequestHeader.class, com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder.class);
    }

    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;

    /**
     * <pre>
     * 命令id
     * </pre>
     *
     * <code>int32 commandId = 1;</code>
     *
     * @return The commandId.
     */
    @java.lang.Override
    public int getCommandId() {
      return commandId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;

    /**
     * <pre>
     * 请求时间戳
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (commandId_ != 0) {
        output.writeInt32(1, commandId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, commandId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(2, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.alonwang.transport.protobuf.Base.RequestHeader)) {
        return super.equals(obj);
      }
      com.github.alonwang.transport.protobuf.Base.RequestHeader other = (com.github.alonwang.transport.protobuf.Base.RequestHeader) obj;

      if (getCommandId()
              != other.getCommandId()) return false;
      if (getTimestamp()
              != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getCommandId();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.alonwang.transport.protobuf.Base.RequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * *
     * 请求头
     * </pre>
     * <p>
     * Protobuf type {@code RequestHeader}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:RequestHeader)
            com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_RequestHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_RequestHeader_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.github.alonwang.transport.protobuf.Base.RequestHeader.class, com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder.class);
      }

      // Construct using com.github.alonwang.transport.protobuf.Base.RequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        commandId_ = 0;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_RequestHeader_descriptor;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.RequestHeader getDefaultInstanceForType() {
        return com.github.alonwang.transport.protobuf.Base.RequestHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.RequestHeader build() {
        com.github.alonwang.transport.protobuf.Base.RequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.RequestHeader buildPartial() {
        com.github.alonwang.transport.protobuf.Base.RequestHeader result = new com.github.alonwang.transport.protobuf.Base.RequestHeader(this);
        result.commandId_ = commandId_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.alonwang.transport.protobuf.Base.RequestHeader) {
          return mergeFrom((com.github.alonwang.transport.protobuf.Base.RequestHeader) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.alonwang.transport.protobuf.Base.RequestHeader other) {
        if (other == com.github.alonwang.transport.protobuf.Base.RequestHeader.getDefaultInstance()) return this;
        if (other.getCommandId() != 0) {
          setCommandId(other.getCommandId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.github.alonwang.transport.protobuf.Base.RequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.alonwang.transport.protobuf.Base.RequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commandId_;

      /**
       * <pre>
       * 命令id
       * </pre>
       *
       * <code>int32 commandId = 1;</code>
       *
       * @return The commandId.
       */
      @java.lang.Override
      public int getCommandId() {
        return commandId_;
      }

      /**
       * <pre>
       * 命令id
       * </pre>
       *
       * <code>int32 commandId = 1;</code>
       *
       * @param value The commandId to set.
       * @return This builder for chaining.
       */
      public Builder setCommandId(int value) {

        commandId_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 命令id
       * </pre>
       *
       * <code>int32 commandId = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearCommandId() {

        commandId_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_;

      /**
       * <pre>
       * 请求时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       *
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }

      /**
       * <pre>
       * 请求时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       *
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 请求时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestHeader)
    }

    // @@protoc_insertion_point(class_scope:RequestHeader)
    private static final com.github.alonwang.transport.protobuf.Base.RequestHeader DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.github.alonwang.transport.protobuf.Base.RequestHeader();
    }

    public static com.github.alonwang.transport.protobuf.Base.RequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestHeader>
            PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
      @java.lang.Override
      public RequestHeader parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.RequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Request)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RequestHeader header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    boolean hasHeader();

    /**
     * <code>.RequestHeader header = 1;</code>
     *
     * @return The header.
     */
    com.github.alonwang.transport.protobuf.Base.RequestHeader getHeader();

    /**
     * <code>.RequestHeader header = 1;</code>
     */
    com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes body = 2;</code>
     *
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }

  /**
   * <pre>
   * *
   * 请求
   * </pre>
   * <p>
   * Protobuf type {@code Request}
   */
  public static final class Request extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Request)
          RequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Request() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Request(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.github.alonwang.transport.protobuf.Base.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_Request_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.github.alonwang.transport.protobuf.Base.Request.class, com.github.alonwang.transport.protobuf.Base.Request.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.github.alonwang.transport.protobuf.Base.RequestHeader header_;

    /**
     * <code>.RequestHeader header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }

    /**
     * <code>.RequestHeader header = 1;</code>
     *
     * @return The header.
     */
    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.RequestHeader getHeader() {
      return header_ == null ? com.github.alonwang.transport.protobuf.Base.RequestHeader.getDefaultInstance() : header_;
    }

    /**
     * <code>.RequestHeader header = 1;</code>
     */
    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;

    /**
     * <code>bytes body = 2;</code>
     *
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, getHeader());
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.alonwang.transport.protobuf.Base.Request)) {
        return super.equals(obj);
      }
      com.github.alonwang.transport.protobuf.Base.Request other = (com.github.alonwang.transport.protobuf.Base.Request) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
                .equals(other.getHeader())) return false;
      }
      if (!getBody()
              .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.Request parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.alonwang.transport.protobuf.Base.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * *
     * 请求
     * </pre>
     * <p>
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Request)
            com.github.alonwang.transport.protobuf.Base.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_Request_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.github.alonwang.transport.protobuf.Base.Request.class, com.github.alonwang.transport.protobuf.Base.Request.Builder.class);
      }

      // Construct using com.github.alonwang.transport.protobuf.Base.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_Request_descriptor;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.Request getDefaultInstanceForType() {
        return com.github.alonwang.transport.protobuf.Base.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.Request build() {
        com.github.alonwang.transport.protobuf.Base.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.Request buildPartial() {
        com.github.alonwang.transport.protobuf.Base.Request result = new com.github.alonwang.transport.protobuf.Base.Request(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.alonwang.transport.protobuf.Base.Request) {
          return mergeFrom((com.github.alonwang.transport.protobuf.Base.Request) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.alonwang.transport.protobuf.Base.Request other) {
        if (other == com.github.alonwang.transport.protobuf.Base.Request.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.github.alonwang.transport.protobuf.Base.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.alonwang.transport.protobuf.Base.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.github.alonwang.transport.protobuf.Base.RequestHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
              com.github.alonwang.transport.protobuf.Base.RequestHeader, com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder, com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder> headerBuilder_;

      /**
       * <code>.RequestHeader header = 1;</code>
       *
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       *
       * @return The header.
       */
      public com.github.alonwang.transport.protobuf.Base.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.github.alonwang.transport.protobuf.Base.RequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(com.github.alonwang.transport.protobuf.Base.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder setHeader(
              com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder mergeHeader(com.github.alonwang.transport.protobuf.Base.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
                    com.github.alonwang.transport.protobuf.Base.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder getHeaderBuilder() {

        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      public com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
                  com.github.alonwang.transport.protobuf.Base.RequestHeader.getDefaultInstance() : header_;
        }
      }

      /**
       * <code>.RequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.github.alonwang.transport.protobuf.Base.RequestHeader, com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder, com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder>
      getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                  com.github.alonwang.transport.protobuf.Base.RequestHeader, com.github.alonwang.transport.protobuf.Base.RequestHeader.Builder, com.github.alonwang.transport.protobuf.Base.RequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

      /**
       * <code>bytes body = 2;</code>
       *
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }

      /**
       * <code>bytes body = 2;</code>
       *
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        body_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes body = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearBody() {

        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final com.github.alonwang.transport.protobuf.Base.Request DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.github.alonwang.transport.protobuf.Base.Request();
    }

    public static com.github.alonwang.transport.protobuf.Base.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
            PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseHeaderOrBuilder extends
          // @@protoc_insertion_point(interface_extends:ResponseHeader)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 命令id
     * </pre>
     *
     * <code>int32 commandId = 1;</code>
     *
     * @return The commandId.
     */
    int getCommandId();

    /**
     * <pre>
     * 响应时间戳
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * 0表示正常 其他表示错误码
     * </pre>
     *
     * <code>int32 errorCode = 3;</code>
     *
     * @return The errorCode.
     */
    int getErrorCode();
  }

  /**
   * <pre>
   * *
   * 响应头
   * </pre>
   * <p>
   * Protobuf type {@code ResponseHeader}
   */
  public static final class ResponseHeader extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:ResponseHeader)
          ResponseHeaderOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ResponseHeader.newBuilder() to construct.
    private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ResponseHeader() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new ResponseHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private ResponseHeader(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              commandId_ = input.readInt32();
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 24: {

              errorCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_ResponseHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_ResponseHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.github.alonwang.transport.protobuf.Base.ResponseHeader.class, com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder.class);
    }

    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;

    /**
     * <pre>
     * 命令id
     * </pre>
     *
     * <code>int32 commandId = 1;</code>
     *
     * @return The commandId.
     */
    @java.lang.Override
    public int getCommandId() {
      return commandId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;

    /**
     * <pre>
     * 响应时间戳
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 3;
    private int errorCode_;

    /**
     * <pre>
     * 0表示正常 其他表示错误码
     * </pre>
     *
     * <code>int32 errorCode = 3;</code>
     *
     * @return The errorCode.
     */
    @java.lang.Override
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (commandId_ != 0) {
        output.writeInt32(1, commandId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(3, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, commandId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(2, timestamp_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.alonwang.transport.protobuf.Base.ResponseHeader)) {
        return super.equals(obj);
      }
      com.github.alonwang.transport.protobuf.Base.ResponseHeader other = (com.github.alonwang.transport.protobuf.Base.ResponseHeader) obj;

      if (getCommandId()
              != other.getCommandId()) return false;
      if (getTimestamp()
              != other.getTimestamp()) return false;
      if (getErrorCode()
              != other.getErrorCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getCommandId();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTimestamp());
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.alonwang.transport.protobuf.Base.ResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * *
     * 响应头
     * </pre>
     * <p>
     * Protobuf type {@code ResponseHeader}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ResponseHeader)
            com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_ResponseHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_ResponseHeader_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.github.alonwang.transport.protobuf.Base.ResponseHeader.class, com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder.class);
      }

      // Construct using com.github.alonwang.transport.protobuf.Base.ResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        commandId_ = 0;

        timestamp_ = 0L;

        errorCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_ResponseHeader_descriptor;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.ResponseHeader getDefaultInstanceForType() {
        return com.github.alonwang.transport.protobuf.Base.ResponseHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.ResponseHeader build() {
        com.github.alonwang.transport.protobuf.Base.ResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.ResponseHeader buildPartial() {
        com.github.alonwang.transport.protobuf.Base.ResponseHeader result = new com.github.alonwang.transport.protobuf.Base.ResponseHeader(this);
        result.commandId_ = commandId_;
        result.timestamp_ = timestamp_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.alonwang.transport.protobuf.Base.ResponseHeader) {
          return mergeFrom((com.github.alonwang.transport.protobuf.Base.ResponseHeader) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.alonwang.transport.protobuf.Base.ResponseHeader other) {
        if (other == com.github.alonwang.transport.protobuf.Base.ResponseHeader.getDefaultInstance()) return this;
        if (other.getCommandId() != 0) {
          setCommandId(other.getCommandId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.github.alonwang.transport.protobuf.Base.ResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.alonwang.transport.protobuf.Base.ResponseHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commandId_;

      /**
       * <pre>
       * 命令id
       * </pre>
       *
       * <code>int32 commandId = 1;</code>
       *
       * @return The commandId.
       */
      @java.lang.Override
      public int getCommandId() {
        return commandId_;
      }

      /**
       * <pre>
       * 命令id
       * </pre>
       *
       * <code>int32 commandId = 1;</code>
       *
       * @param value The commandId to set.
       * @return This builder for chaining.
       */
      public Builder setCommandId(int value) {

        commandId_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 命令id
       * </pre>
       *
       * <code>int32 commandId = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearCommandId() {

        commandId_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_;

      /**
       * <pre>
       * 响应时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       *
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }

      /**
       * <pre>
       * 响应时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       *
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 响应时间戳
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int errorCode_;

      /**
       * <pre>
       * 0表示正常 其他表示错误码
       * </pre>
       *
       * <code>int32 errorCode = 3;</code>
       *
       * @return The errorCode.
       */
      @java.lang.Override
      public int getErrorCode() {
        return errorCode_;
      }

      /**
       * <pre>
       * 0表示正常 其他表示错误码
       * </pre>
       *
       * <code>int32 errorCode = 3;</code>
       *
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {

        errorCode_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 0表示正常 其他表示错误码
       * </pre>
       *
       * <code>int32 errorCode = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {

        errorCode_ = 0;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:ResponseHeader)
    private static final com.github.alonwang.transport.protobuf.Base.ResponseHeader DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.github.alonwang.transport.protobuf.Base.ResponseHeader();
    }

    public static com.github.alonwang.transport.protobuf.Base.ResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseHeader>
            PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
      @java.lang.Override
      public ResponseHeader parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.ResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Response)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ResponseHeader header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    boolean hasHeader();

    /**
     * <code>.ResponseHeader header = 1;</code>
     *
     * @return The header.
     */
    com.github.alonwang.transport.protobuf.Base.ResponseHeader getHeader();

    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes body = 2;</code>
     *
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }

  /**
   * <pre>
   * *
   * 响应
   * </pre>
   * <p>
   * Protobuf type {@code Response}
   */
  public static final class Response extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Response)
          ResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Response() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Response(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.github.alonwang.transport.protobuf.Base.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.github.alonwang.transport.protobuf.Base.internal_static_Response_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.github.alonwang.transport.protobuf.Base.Response.class, com.github.alonwang.transport.protobuf.Base.Response.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.github.alonwang.transport.protobuf.Base.ResponseHeader header_;

    /**
     * <code>.ResponseHeader header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }

    /**
     * <code>.ResponseHeader header = 1;</code>
     *
     * @return The header.
     */
    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.ResponseHeader getHeader() {
      return header_ == null ? com.github.alonwang.transport.protobuf.Base.ResponseHeader.getDefaultInstance() : header_;
    }

    /**
     * <code>.ResponseHeader header = 1;</code>
     */
    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;

    /**
     * <code>bytes body = 2;</code>
     *
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, getHeader());
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.github.alonwang.transport.protobuf.Base.Response)) {
        return super.equals(obj);
      }
      com.github.alonwang.transport.protobuf.Base.Response other = (com.github.alonwang.transport.protobuf.Base.Response) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
                .equals(other.getHeader())) return false;
      }
      if (!getBody()
              .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static com.github.alonwang.transport.protobuf.Base.Response parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.github.alonwang.transport.protobuf.Base.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * *
     * 响应
     * </pre>
     * <p>
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Response)
            com.github.alonwang.transport.protobuf.Base.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_Response_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.github.alonwang.transport.protobuf.Base.Response.class, com.github.alonwang.transport.protobuf.Base.Response.Builder.class);
      }

      // Construct using com.github.alonwang.transport.protobuf.Base.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.github.alonwang.transport.protobuf.Base.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.Response getDefaultInstanceForType() {
        return com.github.alonwang.transport.protobuf.Base.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.Response build() {
        com.github.alonwang.transport.protobuf.Base.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.alonwang.transport.protobuf.Base.Response buildPartial() {
        com.github.alonwang.transport.protobuf.Base.Response result = new com.github.alonwang.transport.protobuf.Base.Response(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.alonwang.transport.protobuf.Base.Response) {
          return mergeFrom((com.github.alonwang.transport.protobuf.Base.Response) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.alonwang.transport.protobuf.Base.Response other) {
        if (other == com.github.alonwang.transport.protobuf.Base.Response.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.github.alonwang.transport.protobuf.Base.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.alonwang.transport.protobuf.Base.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.github.alonwang.transport.protobuf.Base.ResponseHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
              com.github.alonwang.transport.protobuf.Base.ResponseHeader, com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder, com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder> headerBuilder_;

      /**
       * <code>.ResponseHeader header = 1;</code>
       *
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       *
       * @return The header.
       */
      public com.github.alonwang.transport.protobuf.Base.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.github.alonwang.transport.protobuf.Base.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(com.github.alonwang.transport.protobuf.Base.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
              com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(com.github.alonwang.transport.protobuf.Base.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
                    com.github.alonwang.transport.protobuf.Base.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder getHeaderBuilder() {

        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      public com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
                  com.github.alonwang.transport.protobuf.Base.ResponseHeader.getDefaultInstance() : header_;
        }
      }

      /**
       * <code>.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.github.alonwang.transport.protobuf.Base.ResponseHeader, com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder, com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder>
      getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                  com.github.alonwang.transport.protobuf.Base.ResponseHeader, com.github.alonwang.transport.protobuf.Base.ResponseHeader.Builder, com.github.alonwang.transport.protobuf.Base.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

      /**
       * <code>bytes body = 2;</code>
       *
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }

      /**
       * <code>bytes body = 2;</code>
       *
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        body_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes body = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearBody() {

        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.github.alonwang.transport.protobuf.Base.Response DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.github.alonwang.transport.protobuf.Base.Response();
    }

    public static com.github.alonwang.transport.protobuf.Base.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
            PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.alonwang.transport.protobuf.Base.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_RequestHeader_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Request_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_ResponseHeader_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_ResponseHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Response_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\nbase.proto\"5\n\rRequestHeader\022\021\n\tcommand" +
                    "Id\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\003\"7\n\007Request\022\036" +
                    "\n\006header\030\001 \001(\0132\016.RequestHeader\022\014\n\004body\030\002" +
                    " \001(\014\"I\n\016ResponseHeader\022\021\n\tcommandId\030\001 \001(" +
                    "\005\022\021\n\ttimestamp\030\002 \001(\003\022\021\n\terrorCode\030\003 \001(\005\"" +
                    "9\n\010Response\022\037\n\006header\030\001 \001(\0132\017.ResponseHe" +
                    "ader\022\014\n\004body\030\002 \001(\014B(\n&com.github.alonwan" +
                    "g.transport.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    });
    internal_static_RequestHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_RequestHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_RequestHeader_descriptor,
            new java.lang.String[]{"CommandId", "Timestamp",});
    internal_static_Request_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Request_descriptor,
            new java.lang.String[]{"Header", "Body",});
    internal_static_ResponseHeader_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ResponseHeader_descriptor,
            new java.lang.String[]{"CommandId", "Timestamp", "ErrorCode",});
    internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(3);
    internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Response_descriptor,
            new java.lang.String[]{"Header", "Body",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
